package fi.utu.tech.telephonegame;

import java.util.ArrayList;

import fi.utu.tech.telephonegame.ui.MainViewController;
import javafx.application.Platform;

/**
 * DO NOT EDIT THIS FILE. - ÄLÄ MUOKKAA TÄTÄ TIEDOSTOA.
 * 
 * The idea of this class is to provide is abstraction between UI and business logic.
 * 
 * It is used to send data to the UI and to receive events created by user.
 * The events are passed to MessageBroker.
 * 
 */

public class Gui_io {

	private MainViewController controller;
	private MessageBroker broker;

	public Gui_io(MainViewController controller) {
		this.controller = controller;
	}

	
	/*
	 * setReceivedMessage method is used to set the text in the Received message text area
	 */
	public void setReceivedMessage(String text) {
		controller.setReceivedMessage(text);
	}

	
	/*
	 * setRefinedMessage method is used to set the text in the Refined message text area
	 */
	public void setRefinedMessage(String text) {
		controller.setRefinedMessage(text);
	}
	
	/*
	 * setSignal method is used to change the color of the color area
	 */
	public void setSignal(Integer value) {
		controller.setSignal(value);
	}

	
	// Method below this point are not needed in the assignment. They are only used by the template.
	
	public void enableConnect() {
		controller.enableConnect();
	}
	
	public void setMessageBroker(MessageBroker broker) {
		this.broker = broker;
	}
	
	public void sendNewMessage(String text) {
		broker.send(text);
	}

	public void connect(int netType, boolean rootNode, String rootIPAddress) {
		broker.connect(netType, rootNode, rootIPAddress);
	}

	public ArrayList<String> getIPs() {
		return broker.getIPs();
	}
}
