package fi.utu.tech.telephonegame.ui;

import fi.utu.tech.telephonegame.Gui_io;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ComboBox;
import javafx.scene.control.RadioButton;
import javafx.scene.control.TextArea;
import javafx.scene.control.ToggleGroup;
import javafx.scene.paint.Color;

/**
 * DO NOT EDIT THIS FILE. - ÄLÄ MUOKKAA TÄTÄ TIEDOSTOA.
 * 
 * This class is the JavaFx controller class for the UI
 */

public class MainViewController {

	@FXML
	private Canvas signal;
	@FXML
	private Button SendNewButton;
	@FXML
	private ComboBox<String> ipAddresses;
	@FXML
	private Button connectButton;
	@FXML
	private TextArea receivedMessage;
	@FXML
	private TextArea refinedMessage;
	@FXML
	private TextArea newMessage;
	@FXML
	private RadioButton netSelectionLocal;
	@FXML
	private RadioButton netSelectionPublic;
	@FXML
	private CheckBox setRootNode;

	private Gui_io gui_io;
	private GraphicsContext signalContent;
	private ToggleGroup radioGroup;
	private int netType = 0;
	private boolean rootNode = false;

	public void set_Gui_io(Gui_io gui_io) {
		this.gui_io = gui_io;
	}

	public void addIPs() {
		ipAddresses.getItems().addAll(gui_io.getIPs());
		ipAddresses.getSelectionModel().selectFirst();
	}

	@FXML
	public void initialize() {
		signalContent = signal.getGraphicsContext2D();
		signalContent.setFill(Color.BLUE);
		signalContent.fillRect(0, 0, signal.getWidth(), signal.getHeight());

		radioGroup = new ToggleGroup();
		netSelectionLocal.setToggleGroup(radioGroup);
		netSelectionPublic.setToggleGroup(radioGroup);
		netSelectionLocal.setOnAction(event -> netType = 0);
		netSelectionPublic.setOnAction(event -> netType = 1);
		netSelectionLocal.setSelected(true);
		setRootNode.setOnAction(event -> rootNode = !rootNode);
		ipAddresses.disableProperty().bind(setRootNode.selectedProperty().not());
		
	}

	@FXML
	private void sendNewButtonPressed(ActionEvent event) {
		gui_io.sendNewMessage(newMessage.getText());
		newMessage.clear();
		receivedMessage.clear();
		refinedMessage.clear();
		resetSignal();
	}

	@FXML
	private void connectButtonPressed(ActionEvent event) {
		gui_io.connect(netType, rootNode, ipAddresses.getValue());
		connectButton.setDisable(true);
	}

	private void resetSignal() {
		signalContent.setFill(Color.web("hsl(0,100%,100%)"));
		signalContent.fillRect(0, 0, signal.getWidth(), signal.getHeight());
	}

	public void enableConnect() {
		Platform.runLater(() -> connectButton.setDisable(false));
	}
	
	public void setReceivedMessage(String text) {
		Platform.runLater(() -> receivedMessage.setText(text));
	}

	public void setRefinedMessage(String text) {
		Platform.runLater(() -> refinedMessage.setText(text));
	}

	public void setSignal(Integer value) {
		Platform.runLater(() -> {
			signalContent.setFill(Color.web("hsl(" + value + ",100%,100%)"));
			signalContent.fillRect(0, 0, signal.getWidth(), signal.getHeight());
		});
	}

}
